baseUrl = "https://grafana.com/"
languageCode = "en-us"
title = "Grafana Labs Blog"
canonifyURLs = true
relativeURLs = false
verbose = true
enableRobotsTXT = true
disableSitemap = false
disableRSS = false
rssLimit = 20
preserveTaxonomyNames = true
metaDataFormat = "yaml"

[taxonomies]
category = "categories"

[permalinks]
  blog = ":year/:month/:day/:title/"
