baseurl = "http://localhost:3002/"
languageCode = "en-us"
title = "Beautiful Metrics Dashboards, Data Visualization and Monitoring"
canonifyurls = false
relativeURLs = false
verbose = true
enableRobotsTXT = true
disableSitemap = false
disableRSS = false
preservetaxonomynames = true

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
  blog = ":year/:month/:day/:title/"


