baseurl = "http://localhost:3002/"
languageCode = "en-us"
title = "Grafana Labs Blog"
canonifyurls = true
relativeURLs = false
verbose = true
enableRobotsTXT = true
disableSitemap = false
disableRSS = false
preservetaxonomynames = true

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
  blog = "blog/:year/:month/:day/:title/"


