baseurl = "http://localhost:3002/"
languageCode = "en-us"
title = "Beautiful Metrics Dashboards, Data Visualization and Monitoring"
canonifyurls = false
relativeURLs = false
verbose = true
enableRobotsTXT = true
disableSitemap = false
disableRSS = true

[permalinks]
  blog = "blog/:year/:month/:day/:title/"

[menu]
[[menu.main]]
name = "Welcome to the Docs"
identifer = "root"
url = "/"
weight = -85




